### ISSUE TITLE
Diffenator report

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/lovers-quarrel#5]
Hi @crystaltype, these are the main reports from diffenator

Please inspect them and recover the missing glyphs from the published font if needed; also review/recover the glyphs that have major changes, e.g. `euro` `OE` `Oslash`

![glyphs_missing](https://user-images.githubusercontent.com/48698976/118228532-f9206d00-b44f-11eb-9559-7b496a246de2.gif)
![glyphs_modified](https://user-images.githubusercontent.com/48698976/118228635-21a86700-b450-11eb-9047-417dbe91d520.gif)

**Comment by vv-monsalve** [comment]
### Browser previews

**OS X High Sierra Safari_11**
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/118228904-a09d9f80-b450-11eb-9e9a-bc6b4408c79f.gif)
**Windows 10 Chrome_71**
![Desktop_Windows_10_chrome_71 0_](https://user-images.githubusercontent.com/48698976/118228911-a2fff980-b450-11eb-9f1c-359fc2610dbe.gif)
**Windows 10 Edge_18**
![Desktop_Windows_10_edge_18 0_](https://user-images.githubusercontent.com/48698976/118228914-a3989000-b450-11eb-8b53-610a7b08a87d.gif)

**Comment by crystaltype** [comment]
@vv-monsalve I've recovered the missing glyphs from the published font.
However, I think the "after" version of most of the major changed glyphs are better fitted with the font. ie. Euro in "before" looks too big compared to the rest of the font. Germanbls in the "before" version also looked like it was from another font.

Should I still change those glyphs back to the "before" version?
@davelab6 please let me know what you think

**Comment by vv-monsalve** [comment]
> However, I think the "after" version of most of the major changed glyphs are better fitted with the font. ie. Euro in "before" looks too big compared to the rest of the font. Germanbls in the "before" version also looked like it was from another font.

@crystaltype As we have talked about on other topics, this is also a case by case consideration. Everything that is an improvement could be kept (if it doesn't represent a huge regression for the users). 
However, a quick review of the other glyphs reported as modified should be done. E.g. in this case the `sterling` would be the one that should be reverted, as it's now huge in relation to the past form and especially the new Euro and other currency symbols.

![Screen Shot 2021-05-18 at 07 27 20](https://user-images.githubusercontent.com/48698976/118651913-a4605780-b7ab-11eb-93a6-8505ba51a734.png)
